tasks:
  - func: "/pscratch/sd/t/tpeterka/software/spack/opt/spack/linux-zen3/python-3.13.8-yijjsarxhkp56h7isujo2pzjsffndunj/bin/esm_watermasses.py"
  #- func: "/pscratch/sd/t/tpeterka/software/spack/opt/spack/linux-zen3/esm_watermasses-main-rnejxxwfi2k5ekyri5hiwqvukrjn6qtt/esm_watermasses/watermasses.py"
    nprocs: 1
    #args: ["coords", "parameters_template.yaml"]
    args: ["results", "-f", "0", "parameters_template.yaml"]
    inports:
      - filename: "*v3.GMPAS-JRA1p5_EC30to60E2r2_geom.mpaso.hist.am.timeSeriesStatsMonthly.*.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
    outports:
      - filename: "*.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
