# change the paths below to your own
tasks:
  - func: "/pscratch/sd/t/tpeterka/software/E3SM/ccase2/ccase2/bld/e3sm_shared.so"
    nprocs: 2
    #actions: ["actions", "callback"]
    inports:
      - filename: "*.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
    outports:
      - filename: "*ccase2.mpaso.hist.am.globalStats.0001-01-01.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
  #- func: "/global/homes/t/tpeterka/software/e3sm-workflow/analysis.py"
  - func: "/global/homes/t/tpeterka/software/e3sm-workflow/install/bin/consumer.so"
    nprocs: 1
    #args: ["--filename", "ccase2.mpaso.hist.am.globalStats.0001-01-01.nc", "--dataset", "xtime"]
    args: ["-f", "ccase2.mpaso.hist.am.globalStats.0001-01-01.nc"]
    inports:
      - filename: "*ccase2.mpaso.hist.am.globalStats.0001-01-01.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
