# change the paths below to your own
tasks:
  - func: "/pscratch/sd/t/tpeterka/software/E3SM/ccase2/ccase2/bld/e3sm_shared.so"
    nprocs: 2
    actions: ["actions", "callback"]
    inports:
      - filename: "*.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
    outports:
      - filename: "*ccase2.mpaso.rst.0001-01-06_00000.nc"
        dsets:
          - name: "*"
            passthru: 0
            metadata: 1
  - func: "/global/homes/t/tpeterka/software/e3sm-workflow/analysis.py"
    nprocs: 1
    args: ["--filename", "/pscratch/sd/t/tpeterka/software/E3SM/ccase2/ccase2/run/ccase2.mpaso.rst.0001-01-06_00000.nc", "--dataset", "xtime"]
    inports:
      - filename: "*ccase2.mpaso.rst.0001-01-06_00000.nc"
        dsets:
          - name: "*"
            passthru: 0
            metadata: 1
