tasks:
  - func: "/global/homes/t/tpeterka/software/e3sm-workflow/analysis.py"
    nprocs: 1
    args: ["--infile", "ccase2.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc", "--dataset", "ssh"]
    inports:
      - filename: "*ccase2.mpaso.hist.am.highFrequencyOutput.0001-01-01_00.00.00.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
